# -*- mode: ruby -*-
# vi: set ft=ruby :
usr_src_disk = './usr_src.vdi'
usr_obj_disk = './usr_obj.vdi'
Vagrant.configure("2") do |config|
  kernconf_file = ENV['ARTIFACTS_KERNCONF']
  kernconf = ENV['ARTIFACTS_KERNCONF']
  kernconf = kernconf || 'GENERIC'
  build_opts = "KERNCONF=" + kernconf
  bsd_version = ENV['ARTIFACTS_BSD_VERSION'] 
  bsd_version = bsd_version || '14.0'
  config.vm.guest = :freebsd
  if kernconf_file and File.exist?(kernconf_file)
    config.vm.provision "file", source: kernconf_file, destination: '/tmp/'+kernconf
  end
  config.vm.box = 'freebsd/FreeBSD-'+bsd_version+'-RELEASE'
  #config.vm.box_version = "2023.11.10"
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D14C66"
  config.vm.provider "virtualbox" do |v|
    unless File.exist?(usr_src_disk)
      v.customize ['createhd', '--filename', usr_src_disk, '--variant', 'Fixed', '--size', 5 * 1024]
    end
    unless File.exist?(usr_obj_disk)
      v.customize ['createhd', '--filename', usr_obj_disk, '--variant', 'Fixed', '--size', 20 * 1024]
    end
    v.memory= "2048"
    v.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', usr_src_disk]
    v.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 1, '--type', 'hdd', '--medium', usr_obj_disk]
    v.cpus="4"
  end
  config.vm.provision "shell", inline: "newfs /dev/ada1 && mkdir -p /usr/src && mount /dev/ada1 /usr/src"
  config.vm.provision "shell", inline: "newfs /dev/ada2 && mkdir -p /usr/obj && mount /dev/ada2 /usr/obj"
  config.vm.provision "shell", inline: "pkg install -y git-lite"
  config.vm.provision "shell", inline: "git clone -b main --depth=1 https://git.freebsd.org/src.git /usr/src/current"
  if kernconf_file and File.exist?(kernconf_file)
    config.vm.provision "shell", inline: "cp /tmp/" + ENV['ARTIFACTS_KERNCONF'] + " /usr/src/current/sys/amd64/conf/" + ENV['ARTIFACTS_KERNCONF']
  end
  config.vm.provision "shell", inline: "cd /usr/src/current && make -j4 buildworld "+build_opts+" && make -j4 buildkernel "+build_opts+" && make installkernel"+build_opts
  # mostly interested in our build artifacts -- not calling mergemaster to edit configs or install world / pkg upgrade for an actual system upgrade
  config.vm.provision "shell", inline: "shutdown -r now"  
end
